#Instead of using TAB for indentation, use two spaces at the place of one TAB#Controller to control robot arm joints
robot_arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_a1, joint_a2, joint_a3, joint_a4, joint_a5, joint_a6]

#Controller to continuously publish joint states/positions
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50
